// Library 홈 스모크 — 히어로 속도, 히트맵 팝오버, 블록 실패 격리.
import { chromium } from 'playwright';
const BASE = 'http://127.0.0.1:8766';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' }).catch(() => chromium.launch());
const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
const t0 = Date.now();
await p.goto(`${BASE}/v2/library`);
await p.waitForSelector('text=부터 내가 달린 거리');
console.log('hero ms', Date.now() - t0);
await p.waitForSelector('text=내 데이터 출처');
const tabs = await p.locator('nav[aria-label="Library 섹션"] a').allTextContents();
console.log('tabs', tabs.join('|'));
await p.screenshot({ path: '/tmp/lib_home.png', fullPage: true });
const rect = p.locator('svg[aria-label="최근 1년 러닝 캘린더"] rect').nth(300);
await rect.scrollIntoViewIfNeeded();
await rect.dispatchEvent("click");
console.log('popover', await p.locator('[role=status]').first().textContent().catch(() => 'none'));
await p.keyboard.press('Escape');
await p.getByRole('tab', { name: '월별 거리' }).click();
console.log('monthly bars', await p.locator('a[href*="activities?month="]').count());
await p.getByRole('button', { name: /회 ·/ }).click();
console.log('evidence', await p.locator('[role=note]').count());
await p.keyboard.press('Escape');
console.log('evidence after esc', await p.locator('[role=note]').count());
await p.fill('input[type=search]', '롱런');
await p.keyboard.press('Enter');
await p.waitForURL(/activities\?q=/);
console.log('search url', p.url());
// 실패 격리
const p2 = await ctx.newPage();
await p2.route('**/api/v1/library/activities?per_page=5', (r) => r.abort());
await p2.goto(`${BASE}/v2/library`);
await p2.waitForSelector('text=부터 내가 달린 거리');
await p2.waitForSelector('text=내 데이터 출처');
await p2.waitForTimeout(1500);
await p2.screenshot({ path: '/tmp/lib_home_err.png', fullPage: true });
console.log('isolated: hero ok, sources ok, text has retry:', /다시/.test(await p2.locator('body').innerText()));
console.log('pageerrors', errs.length, errs.slice(0, 2));
await b.close();
