import { chromium } from 'playwright';
const BASE='http://localhost:5199', API='http://localhost:18098';
const b=await chromium.launch(); const ctx=await b.newContext({viewport:{width:420,height:900},hasTouch:true});
await ctx.route('**/api/v1/**', r=>r.continue({url:r.request().url().replace(/^https?:\/\/[^/]+/,API)}));
const p=await ctx.newPage(); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto(`${BASE}/v2/library/wellness`,{waitUntil:'networkidle'});
console.log('redirect', p.url());
await p.goto(`${BASE}/v2/library/wellness?date=2026-10-03`,{waitUntil:'networkidle'});
console.log('?date →', p.url());
await p.waitForSelector('text=30일 추세'); await p.waitForTimeout(1500);
await p.screenshot({path:'shots/s5_day.png',fullPage:true});
console.log('chips', await p.locator('section[aria-label=요약] a').allInnerTexts());
const h=await p.evaluate(()=>history.length);
await p.getByRole('button',{name:/이전/}).first().click().catch(e=>console.log('prev btn?',e.message.slice(0,80)));
await p.waitForTimeout(800); console.log('after prev', p.url(), 'hist', h, await p.evaluate(()=>history.length));
await p.goto(`${BASE}/v2/library/wellness/2026-13-45`,{waitUntil:'networkidle'});
console.log('bad:', (await p.locator('body').innerText()).slice(0,80).replace(/\n/g,' '));
await p.goto(`${BASE}/v2/library/wellness/2099-01-01`,{waitUntil:'networkidle'}); console.log('future →',p.url());
await p.goto(`${BASE}/v2/library/wellness/2020-01-01`,{waitUntil:'networkidle'});
console.log('empty:', (await p.locator('body').innerText()).replace(/\n/g,' ').slice(0,200));
await p.screenshot({path:'shots/s5_empty.png'});
console.log('errors',errs);
await b.close();
