"""메트릭 정의 — Layer 2 efficiency~meta/athlete 도메인. metric_registry가 합쳐서 사용."""
from __future__ import annotations

from src.utils.metric_def import MetricDef

MISC_DEFS: list[MetricDef] = [
    # ── efficiency ──
    MetricDef("efficiency_factor", "efficiency", "metric", "", "Efficiency Factor (NGP/HR)",
              aliases={"intervals": "icu_efficiency_factor"}),
    MetricDef("aerobic_decoupling", "efficiency", "metric", "%", "Aerobic Decoupling (%)",
              aliases={"intervals": "icu_decoupling"}),
    MetricDef("variability_index", "efficiency", "metric", "", "Variability Index (NP/AP)"),
    MetricDef("pace_variation", "efficiency", "metric", "", "Pace Variation",
              aliases={"intervals": "pace_variation"}),
    MetricDef("aerobic_decoupling_rp", "efficiency", "metric", "%", "RunPulse 유산소 분리"),
    MetricDef("efficiency_factor_rp", "efficiency", "metric", "", "RunPulse 효율 계수 (EF)"),
    MetricDef("teroi", "efficiency", "metric", "", "TEROI (훈련 효과 ROI)"),
    MetricDef("tpdi", "efficiency", "metric", "%", "TPDI (실내/실외 격차 지수)"),
    MetricDef("rec", "efficiency", "metric", "", "REC (통합 러닝 효율성)", scope="daily"),

    # ── capacity (체력/역량) ──
    MetricDef("vo2max_activity", "capacity", "metric", "ml/kg/min", "활동별 VO2Max 추정치",
              aliases={"garmin": "vO2MaxValue"}),
    MetricDef("vdot", "capacity", "metric", "", "Jack Daniels VDOT"),
    MetricDef("gap", "capacity", "metric", "sec/km", "Grade Adjusted Pace",
              aliases={"intervals": "icu_gap", "garmin": "avgGradeAdjustedSpeed"}),
    MetricDef("endurance_score", "capacity", "metric", "", "Garmin 지구력 점수",
              aliases={"garmin": "enduranceScore"}),
    MetricDef("effective_vo2max", "capacity", "metric", "ml/kg/min", "Runalyze eVO2Max",
              aliases={"runalyze": "effective_vo2max"}),
    MetricDef("lactate_threshold_hr", "capacity", "metric", "bpm", "젖산 역치 심박수",
              aliases={"garmin": "lactateThresholdBpm"}),
    MetricDef("lactate_threshold_speed", "capacity", "metric", "m/s", "젖산 역치 속도",
              aliases={"garmin": "lactateThresholdSpeed"}),
    MetricDef("gap_rp", "capacity", "metric", "sec/km", "RunPulse GAP (경사 보정 페이스)"),
    MetricDef("runpulse_vdot", "capacity", "metric", "", "RunPulse VDOT (Daniels)"),
    MetricDef("race_pred_vdot", "prediction", "metric", "", "예측 결합 VDOT(15℃ 등가)", scope="daily"),
    MetricDef("hr_profile", "hr", "metric", "bpm", "HR 프로필(자체·참조 HRmax/LTHR, HRR·LTHR 존)", scope="daily"),
    MetricDef("hrmax_self", "hr", "metric", "bpm", "RunPulse 추정 최대심박", scope="daily"),
    MetricDef("lthr_self", "hr", "metric", "bpm", "RunPulse 추정 LTHR", scope="daily"),
    MetricDef("lthr_ref", "hr", "metric", "bpm", "기기 제공 LTHR(참조)", scope="daily"),
    MetricDef("hrmax_ref", "hr", "metric", "bpm", "기기/설정 최대심박(참조)", scope="daily"),
    MetricDef("lt_speed_ref", "hr", "metric", "m/s", "기기 제공 역치 속도(참조)", scope="daily"),
    MetricDef("garmin_ftp", "capacity", "metric", "W", "Garmin 러닝 FTP", scope="daily"),
    MetricDef("training_response", "load", "metric", "min/wk", "훈련 반응(역치 이상 주간 분·추세)", scope="daily"),
    MetricDef("fearp", "capacity", "metric", "sec/km", "Field-Equivalent Adjusted Running Pace"),
    MetricDef("critical_power", "capacity", "metric", "W", "Critical Power (CP)", scope="daily"),
    MetricDef("eftp", "capacity", "metric", "sec/km", "eFTP (역치 페이스)", scope="daily"),
    MetricDef("vdot_adj", "capacity", "metric", "", "VDOT 보정", scope="daily"),
    MetricDef("marathon_shape", "capacity", "metric", "%", "Marathon Shape (훈련 완성도)", scope="daily"),
    MetricDef("sapi", "capacity", "metric", "", "SAPI (계절 성과 비교)", scope="daily"),
    MetricDef("rri", "capacity", "metric", "", "RRI (레이스 준비도)", scope="daily"),
    MetricDef("vo2max", "capacity", "metric", "ml/kg/min", "일별 VO2Max 추정치 (Garmin wellness)", scope="daily"),
    MetricDef("di", "capacity", "metric", "", "Durability Index", scope="weekly"),

    # ── prediction ──
    MetricDef("predicted_5k_sec", "prediction", "metric", "sec", "Garmin 5K 예측"),
    MetricDef("predicted_10k_sec", "prediction", "metric", "sec", "Garmin 10K 예측"),
    MetricDef("predicted_half_sec", "prediction", "metric", "sec", "Garmin 하프 예측"),
    MetricDef("predicted_full_sec", "prediction", "metric", "sec", "Garmin 마라톤 예측"),
    MetricDef("race_pred_5k_sec", "prediction", "metric", "sec", "5K 예측 기록", scope="daily",
              aliases={"garmin": "raceTime5K", "runalyze": "prediction_5k"}),
    MetricDef("race_pred_10k_sec", "prediction", "metric", "sec", "10K 예측 기록", scope="daily",
              aliases={"garmin": "raceTime10K", "runalyze": "prediction_10k"}),
    MetricDef("race_pred_half_sec", "prediction", "metric", "sec", "하프마라톤 예측 기록", scope="daily",
              aliases={"garmin": "raceTimeHalf", "runalyze": "prediction_half"}),
    MetricDef("race_pred_marathon_sec", "prediction", "metric", "sec", "마라톤 예측 기록", scope="daily",
              aliases={"garmin": "raceTimeMarathon", "runalyze": "prediction_marathon"}),

    # ── sleep (metric_store 보충) ──
    MetricDef("sleep_deep_sec", "sleep", "metric", "sec", "깊은 수면 시간", scope="daily",
              aliases={"garmin": "deepSleepSeconds"}),
    MetricDef("sleep_light_sec", "sleep", "metric", "sec", "얕은 수면 시간", scope="daily",
              aliases={"garmin": "lightSleepSeconds"}),
    MetricDef("sleep_rem_sec", "sleep", "metric", "sec", "REM 수면 시간", scope="daily",
              aliases={"garmin": "remSleepSeconds"}),
    MetricDef("sleep_awake_sec", "sleep", "metric", "sec", "깨어있던 시간", scope="daily",
              aliases={"garmin": "awakeSleepSeconds"}),
    MetricDef("avg_spo2", "sleep", "metric", "%", "평균 SpO2", scope="daily",
              aliases={"garmin": "averageSpO2Value"}),
    MetricDef("min_spo2", "sleep", "metric", "%", "최저 SpO2", scope="daily",
              aliases={"garmin": "lowestSpO2Value"}),
    MetricDef("avg_respiration_sleep", "sleep", "metric", "brpm", "수면 중 평균 호흡수", scope="daily",
              aliases={"garmin": "averageRespirationValue"}),
    MetricDef("min_respiration_sleep", "sleep", "metric", "brpm", "수면 중 최저 호흡수", scope="daily",
              aliases={"garmin": "lowestRespirationValue"}),
    MetricDef("sleep_avg_hr", "sleep", "metric", "bpm", "수면 중 평균 심박", scope="daily",
              aliases={"garmin": "avgHeartRate"}),
    MetricDef("sleep_body_battery_change", "sleep", "metric", "", "수면 중 Body Battery 충전량", scope="daily",
              aliases={"garmin": "bodyBatteryChange"}),
    MetricDef("skin_temp_deviation", "sleep", "metric", "°C", "수면 중 피부온도 편차", scope="daily",
              aliases={"garmin": "avgSkinTempDeviationC"}),

    # ── stress (상세) ──
    MetricDef("stress_high_duration_sec", "stress", "metric", "sec", "고스트레스 시간", scope="daily",
              aliases={"garmin": "highStressDuration"}),
    MetricDef("stress_medium_duration_sec", "stress", "metric", "sec", "중스트레스 시간", scope="daily",
              aliases={"garmin": "mediumStressDuration"}),
    MetricDef("stress_low_duration_sec", "stress", "metric", "sec", "저스트레스 시간", scope="daily",
              aliases={"garmin": "lowStressDuration"}),
    MetricDef("stress_rest_duration_sec", "stress", "metric", "sec", "휴식 시간", scope="daily",
              aliases={"garmin": "restStressDuration"}),

    # ── readiness ──
    MetricDef("training_readiness_score", "readiness", "metric", "", "Garmin 훈련 준비도 점수", scope="daily",
              aliases={"garmin": "score"}),
    MetricDef("training_readiness_level", "readiness", "metric", "", "Garmin 훈련 준비도 레벨", scope="daily",
              aliases={"garmin": "level"}),
    MetricDef("training_readiness_hrv_factor", "readiness", "metric", "%", "훈련 준비도 HRV 요인", scope="daily",
              aliases={"garmin": "hrvFactorPercent"}),
    MetricDef("training_readiness_sleep_factor", "readiness", "metric", "%", "훈련 준비도 수면 요인", scope="daily",
              aliases={"garmin": "sleepScoreFactorPercent"}),
    MetricDef("training_readiness_recovery_factor", "readiness", "metric", "%", "훈련 준비도 회복 요인", scope="daily",
              aliases={"garmin": "recoveryFactorPercent"}),
    MetricDef("crs", "readiness", "metric", "", "CRS (복합 준비도 게이트)", scope="daily"),
    MetricDef("utrs", "readiness", "metric", "", "Unified Training Readiness Score", scope="daily"),
    MetricDef("utrs_body_battery", "readiness", "metric", "", "UTRS 구성요소 - Body Battery 정규화값 (parent: utrs)", scope="daily"),
    MetricDef("utrs_tsb", "readiness", "metric", "", "UTRS 구성요소 - TSB 정규화값 (parent: utrs)", scope="daily"),
    MetricDef("utrs_sleep", "readiness", "metric", "", "UTRS 구성요소 - 수면 점수 정규화값 (parent: utrs)", scope="daily"),
    MetricDef("utrs_hrv", "readiness", "metric", "", "UTRS 구성요소 - HRV 정규화값 (parent: utrs)", scope="daily"),
    MetricDef("utrs_stress", "readiness", "metric", "", "UTRS 구성요소 - 스트레스 정규화값, 역산 (parent: utrs)", scope="daily"),
    MetricDef("cirs", "readiness", "metric", "", "Composite Injury Risk Score", scope="daily"),
    MetricDef("cirs_acwr", "readiness", "metric", "", "CIRS 구성요소 - ACWR 위험도 (parent: cirs)", scope="daily"),
    MetricDef("cirs_lsi", "readiness", "metric", "", "CIRS 구성요소 - LSI 위험도 (parent: cirs)", scope="daily"),
    MetricDef("cirs_consecutive", "readiness", "metric", "", "CIRS 구성요소 - 연속훈련일 위험도 (parent: cirs)", scope="daily"),
    MetricDef("cirs_fatigue", "readiness", "metric", "", "CIRS 구성요소 - 피로도(CTL-TSB) 위험도 (parent: cirs)", scope="daily"),
    MetricDef("rmr", "readiness", "metric", "json", "Runner Maturity Radar", scope="weekly"),

    # ── weather (metric_store) ──
    MetricDef("weather_temp_c", "weather", "metric", "°C", "기온"),
    MetricDef("weather_humidity_pct", "weather", "metric", "%", "습도"),
    MetricDef("weather_dew_point_c", "weather", "metric", "°C", "이슬점"),
    MetricDef("weather_wind_speed_ms", "weather", "metric", "m/s", "풍속"),
    MetricDef("weather_wind_direction_deg", "weather", "metric", "°", "풍향"),
    MetricDef("weather_pressure_hpa", "weather", "metric", "hPa", "기압"),
    MetricDef("weather_condition", "weather", "metric", "", "날씨 상태 텍스트"),
    MetricDef("weather_feels_like_c", "weather", "metric", "°C", "체감 기온"),
    MetricDef("weather_wbgt_c", "weather", "metric", "°C", "WBGT 근사(그늘, BoM 식)"),
    MetricDef("weather_source", "weather", "metric", "", "기상값 출처(open_meteo/device_corrected/device_raw)"),
    MetricDef("heat_model", "weather", "metric", "%/℃", "개인 기온 영향 계수(더위·추위)", scope="daily"),

    # ── body (metric_store) ──
    MetricDef("body_battery_diff", "body", "metric", "", "활동 중 Body Battery 변화",
              aliases={"garmin": "differenceBodyBattery"}),
    MetricDef("calories_active", "body", "metric", "kcal", "활동 칼로리"),
    MetricDef("calories_total", "body", "metric", "kcal", "총 칼로리"),
    MetricDef("floors_climbed", "body", "metric", "count", "오른 층수"),
    MetricDef("intensity_minutes", "body", "metric", "min", "강도 활동 분"),
    MetricDef("respiration_rate", "body", "metric", "brpm", "호흡수"),
    MetricDef("spo2_avg", "body", "metric", "%", "평균 SpO2"),
    MetricDef("water_estimated_ml", "body", "metric", "ml", "추정 수분 소모량",
              aliases={"garmin": "waterEstimated"}),

    # ── meta (metric_store) ──
    MetricDef("source_event_type", "meta", "metric", "", "소스 원본 이벤트 분류",
              aliases={"garmin": "eventType", "strava": "workout_type"}),
    MetricDef("source_sport_type", "meta", "metric", "", "소스 원본 스포츠 하위 분류",
              aliases={"garmin": "sportType", "strava": "sport_type"}),
    MetricDef("achievement_count", "meta", "metric", "", "Strava 업적 수",
              aliases={"strava": "achievement_count"}),
    MetricDef("kudos_count", "meta", "metric", "", "Strava Kudos",
              aliases={"strava": "kudos_count"}),
    MetricDef("pr_count", "meta", "metric", "", "Strava PR 수",
              aliases={"strava": "pr_count"}),
    MetricDef("timezone_offset", "meta", "metric", "", "타임존 오프셋"),
    MetricDef("workout_type_classified", "meta", "metric", "", "RunPulse 워크아웃 분류"),

    # ── athlete ──
    MetricDef("max_hr_setting", "athlete", "metric", "bpm", "설정 최대 심박수", scope="athlete"),
    MetricDef("rest_hr_setting", "athlete", "metric", "bpm", "설정 안정시 심박수", scope="athlete"),
    MetricDef("threshold_pace_setting", "athlete", "metric", "sec/km", "설정 역치 페이스", scope="athlete"),
    MetricDef("weight_setting", "athlete", "metric", "kg", "설정 체중", scope="athlete"),
    MetricDef("ftp_setting", "athlete", "metric", "W", "설정 FTP", scope="athlete"),
    MetricDef("lthr_setting", "athlete", "metric", "bpm", "설정 LTHR", scope="athlete"),
]
